Update pom.xml
masterdany88/erpe pull request #3
Opened 2017-08-04 22:26 UTC by gabrielli696

junit5-check please

2017-08-05 12:44 UTC, masterdany88 requested changes
Some explanation please

2017-08-05 12:44 UTC, masterdany88 commented on src/erpe/pom.xml
> +    </dependency>
What this is? Why jupiter?

2017-08-05 12:44 UTC, masterdany88 commented on src/erpe/pom.xml
> +   </dependency>
Again why version 4. We will start with 5 beta version.

2017-08-05 12:44 UTC, masterdany88 commented on src/erpe/pom.xml
> +        <scope>test</scope>
Do not know what this is.

2017-08-05 12:44 UTC, masterdany88 commented on src/erpe/pom.xml
> +
Where did You get this from?

2017-08-06 00:44 UTC, gabrielli696 commented on src/erpe/pom.xml
> +
All this are plugins which are necessary to use JUnit5 which isn't  official verison.
After official release there will be required changes to official librar.

2017-08-06 00:44 UTC, gabrielli696 commented on src/erpe/pom.xml
> +        <scope>test</scope>
Parametrised test with adnotations as input:
https://github.com/Pragmatists/JUnitParams

2017-08-06 00:44 UTC, gabrielli696 commented on src/erpe/pom.xml
> +   </dependency>
This is actual version we extend with Jupiter

2017-08-06 00:44 UTC, gabrielli696 commented on src/erpe/pom.xml
> +    </dependency>
Jupiter is engine for JUnit5

2017-08-06 07:06 UTC, masterdany88 commented on src/erpe/pom.xml
> +        <scope>test</scope>
We can try this. I do not know this framework, but looks good.

2017-08-06 07:07 UTC, masterdany88 commented on src/erpe/pom.xml
> +   </dependency>
so this is required by juint 5? I've saw junit 5 example without junit 4 dependencies.

2017-08-06 07:07 UTC, masterdany88 commented on src/erpe/pom.xml
> +    </dependency>
ok

2017-08-06 07:07 UTC, masterdany88 approved these changes

2017-08-06 07:08 UTC, merged